/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.poly.ui;

import com.poly.helper.DateHelper;
import com.poly.dao.HoaDonChiDAO;
import com.poly.dao.LoaiChiDAO;
import com.poly.dao.ChiTietChiDAO;
import com.poly.helper.ImageHelper;
import com.poly.helper.NumberHelper;
import com.poly.helper.ShareHelper;
import com.poly.helper.TableHelper;
import com.poly.model.ChiTietChi;
import com.poly.model.ChiTietChiId;
import com.poly.model.HoaDonChi;
import com.poly.model.LoaiChi;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author THANHLONG
 */
public class FrameThemHoaDonChi extends javax.swing.JFrame {

    /**
     * Creates new form FrameThemHoaDonChi
     */
    public FrameThemHoaDonChi() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();
        lblLoaichi = new javax.swing.JLabel();
        cboLoaichi = new javax.swing.JComboBox<>();
        lblNgaychi = new javax.swing.JLabel();
        lblNguoichi = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblSotien = new javax.swing.JLabel();
        txtSotien = new javax.swing.JTextField();
        lblMota = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMota = new javax.swing.JTextArea();
        pnlButton = new javax.swing.JPanel();
        btnRefesh = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDanhsach = new javax.swing.JTable();
        lblNgaygio = new javax.swing.JLabel();
        pnlFooter = new javax.swing.JPanel();
        btnSubmit = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnlHeader.setBackground(new java.awt.Color(102, 102, 102));
        pnlHeader.setLayout(new javax.swing.BoxLayout(pnlHeader, javax.swing.BoxLayout.LINE_AXIS));

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("  THÊM HOÁ ĐƠN CHI");
        lblTitle.setPreferredSize(new java.awt.Dimension(246, 70));
        pnlHeader.add(lblTitle);

        getContentPane().add(pnlHeader, java.awt.BorderLayout.PAGE_START);

        lblLoaichi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLoaichi.setText("Loại Chi:");

        cboLoaichi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboLoaichi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblNgaychi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNgaychi.setText("Ngày Chi: ");

        lblNguoichi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNguoichi.setText("Người Chi:");

        lblUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUsername.setText("username");

        lblSotien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSotien.setText("Số Tiền:");

        txtSotien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSotien.setPreferredSize(new java.awt.Dimension(307, 22));

        lblMota.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMota.setText("Mô Tả");

        txtMota.setColumns(20);
        txtMota.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtMota.setRows(5);
        jScrollPane1.setViewportView(txtMota);

        btnRefesh.setText("Làm Mới");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlButtonLayout = new javax.swing.GroupLayout(pnlButton);
        pnlButton.setLayout(pnlButtonLayout);
        pnlButtonLayout.setHorizontalGroup(
            pnlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRefesh, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );
        pnlButtonLayout.setVerticalGroup(
            pnlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefesh)
                    .addComponent(btnThem))
                .addContainerGap())
        );

        tblDanhsach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Loại Chi", "Số Tiền", "Xoá"
            }
        ));
        jScrollPane2.setViewportView(tblDanhsach);

        lblNgaygio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNgaygio.setText("jLabel1");

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pnlButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLoaichi)
                            .addComponent(lblNguoichi)
                            .addComponent(lblMota))
                        .addGap(36, 36, 36)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMainLayout.createSequentialGroup()
                                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboLoaichi, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNgaychi)
                                    .addComponent(lblSotien))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSotien, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                                    .addComponent(lblNgaygio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLoaichi)
                    .addComponent(cboLoaichi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNgaychi)
                    .addComponent(lblNgaygio))
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSotien)
                            .addComponent(txtSotien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsername)
                            .addComponent(lblNguoichi))))
                .addGap(18, 18, 18)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMota)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        getContentPane().add(pnlMain, java.awt.BorderLayout.CENTER);

        pnlFooter.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnSubmit.setText("OK");
        btnSubmit.setPreferredSize(new java.awt.Dimension(70, 25));
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        pnlFooter.add(btnSubmit);

        btnThoat.setText("Thoát");
        btnThoat.setPreferredSize(new java.awt.Dimension(70, 25));
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        pnlFooter.add(btnThoat);

        getContentPane().add(pnlFooter, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        String loi = checkInput();
        if (loi.equals("")) {
            addToList();
        } else {
            JOptionPane.showMessageDialog(this, loi, "ERROR", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        insertHoaDonChi();
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameThemHoaDonChi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameThemHoaDonChi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameThemHoaDonChi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameThemHoaDonChi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameThemHoaDonChi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefesh;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JComboBox<String> cboLoaichi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblLoaichi;
    private javax.swing.JLabel lblMota;
    private javax.swing.JLabel lblNgaychi;
    private javax.swing.JLabel lblNgaygio;
    private javax.swing.JLabel lblNguoichi;
    private javax.swing.JLabel lblSotien;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlButton;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JTable tblDanhsach;
    private javax.swing.JTextArea txtMota;
    private javax.swing.JTextField txtSotien;
    // End of variables declaration//GEN-END:variables

    List<LoaiChi> listLoaiChi = new ArrayList<>();
    ChiTietChiDAO chiTietChiDAO = new ChiTietChiDAO();
    ArrayList<Object[]> listObject = new ArrayList<>();
    Date ngayGio = new Date();
    boolean status = false;

    private void init() {
        this.setIconImage(ImageHelper.IMAGE);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.setTitle("THÊM HOÁ ĐƠN CHI");
        loadLoaiChi();
        lblUsername.setText(ShareHelper.nguoiDung.getHoten());
        lblNgaygio.setText(DateHelper.toStringFullDate(ngayGio));
    }

    private void loadLoaiChi() {
        if (!listLoaiChi.isEmpty()) {
            listLoaiChi.clear();
        }
        listLoaiChi = new LoaiChiDAO().getListLoaiChi();
        fillComboboxLoaiChi();
    }

    private void fillComboboxLoaiChi() {
        if (cboLoaichi.getItemCount() != 0) {
            cboLoaichi.removeAllItems();
        }
        if (!listLoaiChi.isEmpty()) {
            for (LoaiChi loaiChi : listLoaiChi) {
                cboLoaichi.addItem(loaiChi.getTenloai());
            }
        }
    }

    private void addToList() {
        int i = 0;
        for (Object[] x : listObject) {
            if (Integer.parseInt(x[0].toString()) == listLoaiChi.get(cboLoaichi.getSelectedIndex()).getMaloaichi()) {
                x[2] = Integer.parseInt(x[2].toString()) + Integer.parseInt(txtSotien.getText());
                listObject.remove(i);
                listObject.add(i, x);
                fillToTable();
                return;
            }
            i++;
        }
        Object[] tmp = new Object[4];
        tmp[0] = listLoaiChi.get(cboLoaichi.getSelectedIndex()).getMaloaichi();
        tmp[1] = listLoaiChi.get(cboLoaichi.getSelectedIndex()).getTenloai();
        tmp[2] = txtSotien.getText();
        tmp[3] = txtMota.getText();
        listObject.add(tmp);
        fillToTable();
    }

    private void fillToTable() {
        System.out.println("FillToTable");
        if (listObject != null) {
            DefaultTableModel model = (DefaultTableModel) tblDanhsach.getModel();
            ActionListener actionListener = new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    deleteItemObject(tblDanhsach.getSelectedRow());
                }
            };
            tblDanhsach.getColumnModel().getColumn(3).setCellRenderer(new TableHelper(tblDanhsach, 3, actionListener));
            model.setRowCount(0);
            int count = 0;
            for (Object[] x : listObject) {
                Vector row = new Vector();
                row.add(++count);
                row.add(x[1]);
                row.add(NumberHelper.convertToPrice(Integer.parseInt(x[2].toString())));
                model.addRow(row);
            }
        }
    }

    private void deleteItemObject(int index) {
        if (index < listObject.size()) {
            int choose = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn xoá ?", "CONFIRM",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (choose == JOptionPane.YES_OPTION) {
                listObject.remove(index);
                fillToTable();
            }
        }
    }

    private void insertHoaDonChi() {
        HoaDonChi hoaDonChi = new HoaDonChi();
        hoaDonChi.setNguoiDung(ShareHelper.nguoiDung);
        hoaDonChi.setNgaychi(ngayGio);
        if (new HoaDonChiDAO().addHoaDonChi(hoaDonChi)) {
            int mahd = new HoaDonChiDAO().getLastHoaDonChi().getIdhdchi();
            for (Object[] x : listObject) {
                ChiTietChi chiTietChi = new ChiTietChi();
                chiTietChi.setId(new ChiTietChiId(mahd, Integer.parseInt(x[0].toString())));
                chiTietChi.setSotien(Integer.parseInt(x[2].toString()));
                chiTietChi.setMota(x[3].toString());
                new ChiTietChiDAO().addChiTietChi(chiTietChi);
            }
            JOptionPane.showMessageDialog(this, "Thêm thành công", "Scuccess", JOptionPane.INFORMATION_MESSAGE);
            PanelHoaDonChi.panelHoaDonChi.loadHoaDon();
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Không thành công");
        }
    }

    private String checkInput() {
        String loi = "";
        Color error = new Color(252, 255, 105);
        txtSotien.setBackground(Color.white);
        if (txtSotien.getText().isEmpty()) {
            loi += "Không được để trống số tiền \n";
            txtSotien.setBackground(error);
        } else {
            try {
                if (Integer.parseInt(txtSotien.getText()) <= 0) {
                    loi += "Số tiền phải > 0 \n";
                    txtSotien.setBackground(error);
                }
            } catch (NumberFormatException e) {
                loi += "Số tiền không được chứa ký tự";
                txtSotien.setBackground(error);
            }
        }
        return loi;
    }
    
}
