/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.poly.ui;

import com.poly.helper.DateHelper;
import com.poly.dao.NguoiDungDAO;
import com.poly.helper.ImageHelper;
import com.poly.helper.ShareHelper;
import com.poly.model.NguoiDung;
import java.awt.Color;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author THANHLONG
 */
public class FrameNguoiDung extends javax.swing.JFrame {

    /**
     * Creates new form ThemNguoiDung
     */
    public FrameNguoiDung(NguoiDung nguoiDung) {
        this.nguoiDung = nguoiDung;
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        pnlTitle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();
        lblTendangnhap = new javax.swing.JLabel();
        lblMatkhau = new javax.swing.JLabel();
        lblHoten = new javax.swing.JLabel();
        lblGioitinh = new javax.swing.JLabel();
        txtTendangnhap = new javax.swing.JTextField();
        txtHoten = new javax.swing.JTextField();
        pnlImg = new javax.swing.JPanel();
        lblImg = new javax.swing.JLabel();
        txtMatkhau = new javax.swing.JPasswordField();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        lblNgaysinh = new javax.swing.JLabel();
        lblSodienthoai = new javax.swing.JLabel();
        lblVaitro = new javax.swing.JLabel();
        txtNgaysinh = new com.toedter.calendar.JDateChooser();
        txtSodienthoai = new javax.swing.JTextField();
        rdoAdmin = new javax.swing.JRadioButton();
        rdoUser = new javax.swing.JRadioButton();
        pnlFooter = new javax.swing.JPanel();
        btnThoat = new javax.swing.JButton();
        btnComfirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnlTitle.setBackground(new java.awt.Color(153, 153, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("   Người Dùng");

        javax.swing.GroupLayout pnlTitleLayout = new javax.swing.GroupLayout(pnlTitle);
        pnlTitle.setLayout(pnlTitleLayout);
        pnlTitleLayout.setHorizontalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 456, Short.MAX_VALUE))
        );
        pnlTitleLayout.setVerticalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        getContentPane().add(pnlTitle, java.awt.BorderLayout.PAGE_START);

        lblTendangnhap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTendangnhap.setText("Tên Đăng Nhập:");

        lblMatkhau.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMatkhau.setText("Mật Khẩu:");

        lblHoten.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHoten.setText("Họ Và Tên:");

        lblGioitinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGioitinh.setText("Giới Tính:");

        txtTendangnhap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtHoten.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        pnlImg.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImgMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlImgLayout = new javax.swing.GroupLayout(pnlImg);
        pnlImg.setLayout(pnlImgLayout);
        pnlImgLayout.setHorizontalGroup(
            pnlImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImg, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlImgLayout.setVerticalGroup(
            pnlImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImg, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addContainerGap())
        );

        txtMatkhau.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        buttonGroup1.add(rdoNam);
        rdoNam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdoNam.setText("Nam");

        buttonGroup1.add(rdoNu);
        rdoNu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdoNu.setText("Nữ");

        lblNgaysinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNgaysinh.setText("Ngày Sinh:");

        lblSodienthoai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSodienthoai.setText("Số Điện Thoại:");

        lblVaitro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblVaitro.setText("Vai Trò:");

        txtNgaysinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtSodienthoai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        buttonGroup2.add(rdoAdmin);
        rdoAdmin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdoAdmin.setText("Quản Trị");

        buttonGroup2.add(rdoUser);
        rdoUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdoUser.setText("Nhân Viên");

        pnlFooter.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlFooter.setPreferredSize(new java.awt.Dimension(715, 50));

        btnThoat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnComfirm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnComfirm.setText("Lưu");
        btnComfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFooterLayout = new javax.swing.GroupLayout(pnlFooter);
        pnlFooter.setLayout(pnlFooterLayout);
        pnlFooterLayout.setHorizontalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFooterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnComfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlFooterLayout.setVerticalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFooterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnComfirm)
                    .addComponent(btnThoat))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTendangnhap)
                    .addComponent(lblMatkhau)
                    .addComponent(lblHoten)
                    .addComponent(lblGioitinh)
                    .addComponent(lblNgaysinh)
                    .addComponent(lblSodienthoai)
                    .addComponent(lblVaitro))
                .addGap(18, 18, 18)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addComponent(rdoAdmin)
                        .addGap(18, 18, 18)
                        .addComponent(rdoUser))
                    .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtHoten)
                        .addComponent(txtTendangnhap)
                        .addComponent(txtMatkhau, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                        .addGroup(pnlMainLayout.createSequentialGroup()
                            .addComponent(rdoNam)
                            .addGap(18, 18, 18)
                            .addComponent(rdoNu))
                        .addComponent(txtNgaysinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSodienthoai)))
                .addGap(18, 18, 18)
                .addComponent(pnlImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnlFooter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlMainLayout.createSequentialGroup()
                                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTendangnhap)
                                    .addComponent(txtTendangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblHoten)
                                    .addComponent(txtHoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblMatkhau)
                                    .addComponent(txtMatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblGioitinh)
                                    .addComponent(rdoNam)
                                    .addComponent(rdoNu))
                                .addGap(18, 18, 18)
                                .addComponent(lblNgaysinh))
                            .addComponent(txtNgaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSodienthoai)
                            .addComponent(txtSodienthoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVaitro)
                            .addComponent(rdoAdmin)
                            .addComponent(rdoUser)))
                    .addComponent(pnlImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pnlFooter, javax.swing.GroupLayout.PREFERRED_SIZE, 52, Short.MAX_VALUE))
        );

        getContentPane().add(pnlMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComfirmActionPerformed
        if (update) {
            updateNguoiDung();
        } else {
            addNguoiDung();
        }
        PanelQLNguoiDung.nguoidung.loadAll();

    }//GEN-LAST:event_btnComfirmActionPerformed

    private void lblImgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImgMouseClicked
        JFileChooser jfc = new JFileChooser();
        int choose = jfc.showSaveDialog(null);
        if (choose == JFileChooser.APPROVE_OPTION) {
            imgFileName = ImageHelper.saveLogo("avatar", jfc.getSelectedFile());
        }
        lblImg.setIcon(ImageHelper.loadLogo("avatar", imgFileName));
    }//GEN-LAST:event_lblImgMouseClicked

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameNguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameNguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameNguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameNguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameNguoiDung(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComfirm;
    private javax.swing.JButton btnThoat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblGioitinh;
    private javax.swing.JLabel lblHoten;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblMatkhau;
    private javax.swing.JLabel lblNgaysinh;
    private javax.swing.JLabel lblSodienthoai;
    private javax.swing.JLabel lblTendangnhap;
    private javax.swing.JLabel lblVaitro;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JPanel pnlImg;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlTitle;
    private javax.swing.JRadioButton rdoAdmin;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JRadioButton rdoUser;
    private javax.swing.JTextField txtHoten;
    private javax.swing.JPasswordField txtMatkhau;
    private com.toedter.calendar.JDateChooser txtNgaysinh;
    private javax.swing.JTextField txtSodienthoai;
    private javax.swing.JTextField txtTendangnhap;
    // End of variables declaration//GEN-END:variables

    NguoiDung nguoiDung = new NguoiDung();
    NguoiDungDAO nguoiDungDAO = new NguoiDungDAO();
    String imgFileName = "unknown.jpg";
    boolean update = false;

    private void init() {
        this.setIconImage(ImageHelper.IMAGE);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        this.setLocationRelativeTo(null);
        rdoNam.setSelected(true);
        rdoUser.setSelected(true);
        txtNgaysinh.setDate(new Date());
        lblImg.setIcon(ImageHelper.loadLogo("avatar", imgFileName));
        checkUser();
        if (nguoiDung != null) {
            btnComfirm.setText("Cập Nhật");
            txtTendangnhap.setEditable(false);
            txtTendangnhap.setBackground(new Color(200, 200, 200));
            update = true;
            showDetail();
        }
    }
//tên hàm chứ moẹ gì
    //gán chữ vào ô đó
    //set cho nó chọn 
    private void showDetail() {
        txtTendangnhap.setText(nguoiDung.getUsername());
        txtHoten.setText(nguoiDung.getHoten());
        txtMatkhau.setText(nguoiDung.getPassword());
        rdoNu.setSelected(true);
        if (nguoiDung.getGioitinh()) {
            rdoNam.setSelected(true);
        }
        txtNgaysinh.setDate(nguoiDung.getNgaysinh());
        txtSodienthoai.setText(nguoiDung.getSodienthoai());
        rdoUser.setSelected(true);
        if (nguoiDung.getVaitro()) {
            rdoAdmin.setSelected(true);
        }
        lblImg.setIcon(ImageHelper.loadLogo("avatar", nguoiDung.getHinh()));
    }

    private NguoiDung getModel() {
        NguoiDung nguoiDung = new NguoiDung();
        nguoiDung.setUsername(txtTendangnhap.getText());
        nguoiDung.setHoten(txtHoten.getText());
        nguoiDung.setPassword(String.valueOf(txtMatkhau.getPassword()));
        nguoiDung.setGioitinh(rdoNam.isSelected());
        nguoiDung.setNgaysinh(txtNgaysinh.getDate());
        nguoiDung.setSodienthoai(txtSodienthoai.getText());
        nguoiDung.setVaitro(rdoAdmin.isSelected());
        nguoiDung.setHinh(imgFileName);
        return nguoiDung;
    }

    private void addNguoiDung() {
        String loi = checkInput("add");
        if (!loi.equals("")) {
            JOptionPane.showMessageDialog(this, loi, "Sai dữ liệu", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (nguoiDungDAO.addNguoiDung(getModel())) {
            JOptionPane.showMessageDialog(this, "Thêm Người Dùng Thành Công", "Successful", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            return;
        }
        JOptionPane.showMessageDialog(this, "Thêm Người Dùng Không Thành Công", "Error", JOptionPane.ERROR_MESSAGE);
    }

    private void updateNguoiDung() {
        String loi = checkInput("capnhat");
        if (!loi.equals("")) {
            JOptionPane.showMessageDialog(this, loi, "Sai dữ liệu", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (nguoiDungDAO.updateNguoiDung(getModel())) {
            JOptionPane.showMessageDialog(this, "Cập Nhật Thành Công", "Successful", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            return;
        }
        JOptionPane.showMessageDialog(this, "Cập Nhật Không Thành Công", "Error", JOptionPane.ERROR_MESSAGE);
    }

    private String checkInput(String status) {
        String loi = "";
        Color error = new Color(252, 255, 105);
        txtTendangnhap.setBackground(Color.white);
        txtHoten.setBackground(Color.white);
        txtMatkhau.setBackground(Color.white);
        txtNgaysinh.setBackground(Color.white);
        txtSodienthoai.setBackground(Color.white);

        //Check Username
        if (txtTendangnhap.getText().isEmpty()) {
            loi += "Không được để trống Username \n";
            txtTendangnhap.setBackground(error);
        } else if (txtTendangnhap.getText().length() > 10) {
            loi += "Tên đăng nhập không vượt quá 10 ký tự \n";
            txtTendangnhap.setBackground(error);
        } else if (!txtTendangnhap.getText().matches("\\w+")) {
            loi += "Username không được có ký tự đặc biệt \n";
            txtTendangnhap.setBackground(error);
        } else if (nguoiDungDAO.checkPrimaryKey(txtTendangnhap.getText()) && !status.equals("capnhat")) {
            loi += "Trùng tên đăng nhập \n";
            txtTendangnhap.setBackground(error);
        }

        //Check HoTen
        if (txtHoten.getText().isEmpty()) {
            loi += "Không để trống Họ Tên \n";
            txtHoten.setBackground(error);
        } else if (txtHoten.getText().length() > 50) {
            loi += "Họ Tên không vượt quá 50 ký tự \n";
            txtHoten.setBackground(error);
        }

        //Check MatKhau
        if (txtMatkhau.getPassword().length == 0) {
            loi += "Không để trống mật khẩu \n";
            txtMatkhau.setBackground(error);
        } else if (txtMatkhau.getPassword().length > 50) {
            loi += "Mật khẩu không vượt quá 50 ký tự \n";
            txtMatkhau.setBackground(error);
        }

        //Check NgaySinh
        if (txtNgaysinh.getDate().getTime() > DateHelper.now().getTime()) {
            loi += "Ngày sinh phải trước ngày hiện tại \n";
            txtNgaysinh.setBackground(error);
        }

        if (txtSodienthoai.getText().isEmpty()) {
            loi += "Không được để trống số điện thoại";
            txtSodienthoai.setBackground(error);
        } else if (txtSodienthoai.getText().length() != 10 && !txtSodienthoai.getText().startsWith("0")) {
            loi += "SĐT phải bắt đầu bằng '0' và có 10 chữ số";
            txtSodienthoai.setBackground(error);
        }

        return loi;
    }
    private void checkUser() {
        if (!ShareHelper.nguoiDung.getVaitro()) {
            rdoUser.setEnabled(false);
            rdoAdmin.setEnabled(false);
        }
    }
}
