/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.poly.ui;

import com.poly.helper.DateHelper;
import com.poly.dao.ThongKeDAO;
import com.poly.helper.NumberHelper;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

/**
 *
 * @author THANHLONG
 */
public class PanelThongKe extends javax.swing.JPanel {

    /**
     * Creates new form PanelThongKe
     */
    public PanelThongKe() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();
        pnlDay = new javax.swing.JPanel();
        lblDaytongthu = new javax.swing.JLabel();
        lblDaytongchi = new javax.swing.JLabel();
        lblDaynguoichi = new javax.swing.JLabel();
        lblDaynguoithu = new javax.swing.JLabel();
        pnlMonth = new javax.swing.JPanel();
        lblMonthtongthu = new javax.swing.JLabel();
        lblMonthtongchi = new javax.swing.JLabel();
        lblMonthnguoichi = new javax.swing.JLabel();
        lblMonthnguoithu = new javax.swing.JLabel();
        pnlYear = new javax.swing.JPanel();
        lblYeartongthu = new javax.swing.JLabel();
        lblYeartongchi = new javax.swing.JLabel();
        lblYearnguoichi = new javax.swing.JLabel();
        lblYearnguoithu = new javax.swing.JLabel();
        pnlFooter = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        pnlHeader.setBackground(new java.awt.Color(0, 153, 102));
        pnlHeader.setPreferredSize(new java.awt.Dimension(1000, 70));
        pnlHeader.setLayout(new javax.swing.BoxLayout(pnlHeader, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("  THỐNG KÊ");
        pnlHeader.add(jLabel1);

        add(pnlHeader, java.awt.BorderLayout.PAGE_START);

        pnlMain.setLayout(new java.awt.GridLayout(3, 1));

        pnlDay.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hôm Nay", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        pnlDay.setLayout(new java.awt.GridLayout(1, 0));

        lblDaytongthu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDaytongthu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDaytongthu.setText("Tổng Chi:");
        lblDaytongthu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tổng Thu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        pnlDay.add(lblDaytongthu);

        lblDaytongchi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDaytongchi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDaytongchi.setText("tong thu");
        lblDaytongchi.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tổng Chi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        pnlDay.add(lblDaytongchi);

        lblDaynguoichi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDaynguoichi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDaynguoichi.setText("Người Chi:");
        lblDaynguoichi.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Người Có HĐ Chi Nhiều Nhất", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        pnlDay.add(lblDaynguoichi);

        lblDaynguoithu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDaynguoithu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDaynguoithu.setText("jLabel5");
        lblDaynguoithu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Người Có HĐ Thu Nhiều Nhất", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        pnlDay.add(lblDaynguoithu);

        pnlMain.add(pnlDay);

        pnlMonth.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tháng Này", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        pnlMonth.setLayout(new java.awt.GridLayout(1, 0));

        lblMonthtongthu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMonthtongthu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMonthtongthu.setText("tong thu");
        lblMonthtongthu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tổng Thu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        pnlMonth.add(lblMonthtongthu);

        lblMonthtongchi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMonthtongchi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMonthtongchi.setText("Tổng Thu:");
        lblMonthtongchi.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tổng Chi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        pnlMonth.add(lblMonthtongchi);

        lblMonthnguoichi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMonthnguoichi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMonthnguoichi.setText("Người Chi:");
        lblMonthnguoichi.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Người Có HĐ Chi Nhiều Nhất", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        pnlMonth.add(lblMonthnguoichi);

        lblMonthnguoithu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMonthnguoithu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMonthnguoithu.setText("jLabel5");
        lblMonthnguoithu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Người Có HĐ Thu Nhiều Nhất", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        pnlMonth.add(lblMonthnguoithu);

        pnlMain.add(pnlMonth);

        pnlYear.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Năm Này", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        pnlYear.setLayout(new java.awt.GridLayout(1, 0));

        lblYeartongthu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblYeartongthu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblYeartongthu.setText("tong thu");
        lblYeartongthu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tổng Thu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        pnlYear.add(lblYeartongthu);

        lblYeartongchi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblYeartongchi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblYeartongchi.setText("Tổng Thu:");
        lblYeartongchi.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tổng Chi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        pnlYear.add(lblYeartongchi);

        lblYearnguoichi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblYearnguoichi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblYearnguoichi.setText("Người Chi:");
        lblYearnguoichi.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Người Có HĐ Chi Nhiều Nhất", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        pnlYear.add(lblYearnguoichi);

        lblYearnguoithu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblYearnguoithu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblYearnguoithu.setText("jLabel5");
        lblYearnguoithu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Người Có HĐ Thu Nhiều Nhất", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        pnlYear.add(lblYearnguoithu);

        pnlMain.add(pnlYear);

        add(pnlMain, java.awt.BorderLayout.CENTER);

        pnlFooter.setPreferredSize(new java.awt.Dimension(1000, 50));

        javax.swing.GroupLayout pnlFooterLayout = new javax.swing.GroupLayout(pnlFooter);
        pnlFooter.setLayout(pnlFooterLayout);
        pnlFooterLayout.setHorizontalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        pnlFooterLayout.setVerticalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        add(pnlFooter, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDaynguoichi;
    private javax.swing.JLabel lblDaynguoithu;
    private javax.swing.JLabel lblDaytongchi;
    private javax.swing.JLabel lblDaytongthu;
    private javax.swing.JLabel lblMonthnguoichi;
    private javax.swing.JLabel lblMonthnguoithu;
    private javax.swing.JLabel lblMonthtongchi;
    private javax.swing.JLabel lblMonthtongthu;
    private javax.swing.JLabel lblYearnguoichi;
    private javax.swing.JLabel lblYearnguoithu;
    private javax.swing.JLabel lblYeartongchi;
    private javax.swing.JLabel lblYeartongthu;
    private javax.swing.JPanel pnlDay;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlMonth;
    private javax.swing.JPanel pnlYear;
    // End of variables declaration//GEN-END:variables

    ThongKeDAO thongKeDAO = new ThongKeDAO();
    LocalDate today = LocalDate.now();

    private void init() {
        run();
    }

    private void run() {
        thongKeChiTheoNgay();
        thongKeChiTheoThang();
        thongKeChiTheoNam();
        thongKeThuTheoNgay();
        thongKeThuTheoThang();
        thongKeThuTheoNam();
        thongKeUserChiTheoNgay();
        thongKeUserChiTheoThang();
        thongKeUserChiTheoNam();
        thongKeUserThuTheoNgay();
        thongKeUserThuTheoThang();
        thongKeUserThuTheoNam();
    }

    private void thongKeChiTheoNgay() {
        Object object = thongKeDAO.sp_getTotalChi(today.getDayOfMonth(), today.getMonthValue(), today.getYear());
        if (object != null) {
            lblDaytongchi.setText(NumberHelper.convertToPrice((int) object));
        } else {
            lblDaytongchi.setText(NumberHelper.convertToPrice(0));
        }
    }

    private void thongKeChiTheoThang() {
        Object object = thongKeDAO.sp_getTotalChi(0, today.getMonthValue(), today.getYear());
        if (object != null) {
            lblMonthtongchi.setText(NumberHelper.convertToPrice((int) object));
        } else {
            lblMonthtongchi.setText(NumberHelper.convertToPrice(0));
        }
    }

    private void thongKeChiTheoNam() {
        Object object = thongKeDAO.sp_getTotalChi(0, 0, today.getYear());
        if (object != null) {
            lblYeartongchi.setText(NumberHelper.convertToPrice((int) object));
        } else {
            lblYeartongchi.setText(NumberHelper.convertToPrice(0));
        }
    }

    private void thongKeThuTheoNgay() {
        Object object = thongKeDAO.sp_getTotalThu(today.getDayOfMonth(), today.getMonthValue(), today.getYear());
        if (object != null) {
            lblDaytongthu.setText(NumberHelper.convertToPrice((int) object));
        } else {
            lblDaytongthu.setText(NumberHelper.convertToPrice(0));
        }
    }

    private void thongKeThuTheoThang() {
        Object object = thongKeDAO.sp_getTotalThu(0, today.getMonthValue(), today.getYear());
        if (object != null) {
            lblMonthtongthu.setText(NumberHelper.convertToPrice((int) object));
        } else {
            lblMonthtongthu.setText(NumberHelper.convertToPrice(0));
        }
    }

    private void thongKeThuTheoNam() {
        Object object = thongKeDAO.sp_getTotalThu(0, 0, today.getYear());
        if (object != null) {
            lblYeartongthu.setText(NumberHelper.convertToPrice((int) object));
        } else {
            lblYeartongthu.setText(NumberHelper.convertToPrice(0));
        }
    }

    private void thongKeUserChiTheoNgay() {
        Object object = thongKeDAO.sp_getUserChi(today.getDayOfMonth(), today.getMonthValue(), today.getYear());
        if (object != null) {
            lblDaynguoichi.setText(object.toString());
        } else {
            lblDaynguoichi.setText("N/A");
        }
    }

    private void thongKeUserChiTheoThang() {
        Object object = thongKeDAO.sp_getUserChi(0, today.getMonthValue(), today.getYear());
        if (object != null) {
            lblMonthnguoichi.setText(object.toString());
        } else {
            lblMonthnguoichi.setText("N/A");
        }
    }

    private void thongKeUserChiTheoNam() {
        Object object = thongKeDAO.sp_getUserChi(0, 0, today.getYear());
        if (object != null) {
            lblYearnguoichi.setText(object.toString());
        } else {
            lblYearnguoichi.setText("N/A");
        }
    }
    
    private void thongKeUserThuTheoNgay() {
        Object object = thongKeDAO.sp_getUserThu(today.getDayOfMonth(), today.getMonthValue(), today.getYear());
        if (object != null) {
            lblDaynguoithu.setText(object.toString());
        } else {
            lblDaynguoithu.setText("N/A");
        }
    }
    private void thongKeUserThuTheoThang() {
        Object object = thongKeDAO.sp_getUserThu(0, today.getMonthValue(), today.getYear());
        if (object != null) {
            lblMonthnguoithu.setText(object.toString());
        } else {
            lblMonthnguoithu.setText("N/A");
        }
    }
    private void thongKeUserThuTheoNam() {
        Object object = thongKeDAO.sp_getUserThu(0, 0, today.getYear());
        if (object != null) {
            lblYearnguoithu.setText(object.toString());
        } else {
            lblYearnguoithu.setText("N/A");
        }
    }
}
