package com.poly.model;
// Generated Dec 7, 2019 5:52:52 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChiTietChiId generated by hbm2java
 */
@Embeddable
public class ChiTietChiId implements java.io.Serializable {

    private int mahdchi;
    private int loaichi;

    public ChiTietChiId() {
    }

    public ChiTietChiId(int mahdchi, int loaichi) {
        this.mahdchi = mahdchi;
        this.loaichi = loaichi;
    }

    @Column(name = "mahdchi", nullable = false)
    public int getMahdchi() {
        return this.mahdchi;
    }

    public void setMahdchi(int mahdchi) {
        this.mahdchi = mahdchi;
    }

    @Column(name = "loaichi", nullable = false)
    public int getLoaichi() {
        return this.loaichi;
    }

    public void setLoaichi(int loaichi) {
        this.loaichi = loaichi;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof ChiTietChiId)) {
            return false;
        }
        ChiTietChiId castOther = (ChiTietChiId) other;

        return (this.getMahdchi() == castOther.getMahdchi())
                && (this.getLoaichi() == castOther.getLoaichi());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getMahdchi();
        result = 37 * result + this.getLoaichi();
        return result;
    }

}
