package com.poly.model;
// Generated Dec 7, 2019 5:52:52 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ChiTietThu generated by hbm2java
 */
@Entity
@Table(name="ChiTietThu"
    ,schema="dbo"
    ,catalog="DuAn1"
)
public class ChiTietThu  implements java.io.Serializable {


     private ChiTietThuId id;
     private HoaDonThu hoaDonThu;
     private LoaiThu loaiThu;
     private String mota;
     private Integer sotien;

    public ChiTietThu() {
    }

	
    public ChiTietThu(ChiTietThuId id, HoaDonThu hoaDonThu, LoaiThu loaiThu) {
        this.id = id;
        this.hoaDonThu = hoaDonThu;
        this.loaiThu = loaiThu;
    }
    public ChiTietThu(ChiTietThuId id, HoaDonThu hoaDonThu, LoaiThu loaiThu, String mota, Integer sotien) {
       this.id = id;
       this.hoaDonThu = hoaDonThu;
       this.loaiThu = loaiThu;
       this.mota = mota;
       this.sotien = sotien;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="mahdthu", column=@Column(name="mahdthu", nullable=false) ), 
        @AttributeOverride(name="loaithu", column=@Column(name="loaithu", nullable=false) ) } )
    public ChiTietThuId getId() {
        return this.id;
    }
    
    public void setId(ChiTietThuId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mahdthu", nullable=false, insertable=false, updatable=false)
    public HoaDonThu getHoaDonThu() {
        return this.hoaDonThu;
    }
    
    public void setHoaDonThu(HoaDonThu hoaDonThu) {
        this.hoaDonThu = hoaDonThu;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="loaithu", nullable=false, insertable=false, updatable=false)
    public LoaiThu getLoaiThu() {
        return this.loaiThu;
    }
    
    public void setLoaiThu(LoaiThu loaiThu) {
        this.loaiThu = loaiThu;
    }

    
    @Column(name="mota")
    public String getMota() {
        return this.mota;
    }
    
    public void setMota(String mota) {
        this.mota = mota;
    }

    
    @Column(name="sotien")
    public Integer getSotien() {
        return this.sotien;
    }
    
    public void setSotien(Integer sotien) {
        this.sotien = sotien;
    }




}


