package com.poly.model;
// Generated Dec 7, 2019 5:52:52 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HoaDonChi generated by hbm2java
 */
@Entity
@Table(name = "HoaDonChi",
         schema = "dbo",
         catalog = "DuAn1"
)
public class HoaDonChi implements java.io.Serializable {

    private int idhdchi;
    private NguoiDung nguoiDung;
    private Date ngaychi;
    private Set<ChiTietChi> chiTietChis = new HashSet<ChiTietChi>(0);

    public HoaDonChi() {
    }

    public HoaDonChi(int idhdchi, NguoiDung nguoiDung) {
        this.idhdchi = idhdchi;
        this.nguoiDung = nguoiDung;
    }

    public HoaDonChi(int idhdchi, NguoiDung nguoiDung, Date ngaychi, Set<ChiTietChi> chiTietChis) {
        this.idhdchi = idhdchi;
        this.nguoiDung = nguoiDung;
        this.ngaychi = ngaychi;
        this.chiTietChis = chiTietChis;
    }

    @Id
    @Column(name = "idhdchi", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public int getIdhdchi() {
        return this.idhdchi;
    }

    public void setIdhdchi(int idhdchi) {
        this.idhdchi = idhdchi;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "username", nullable = false)
    public NguoiDung getNguoiDung() {
        return this.nguoiDung;
    }

    public void setNguoiDung(NguoiDung nguoiDung) {
        this.nguoiDung = nguoiDung;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ngaychi", length = 23)
    public Date getNgaychi() {
        return this.ngaychi;
    }

    public void setNgaychi(Date ngaychi) {
        this.ngaychi = ngaychi;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "hoaDonChi")
    public Set<ChiTietChi> getChiTietChis() {
        return this.chiTietChis;
    }

    public void setChiTietChis(Set<ChiTietChi> chiTietChis) {
        this.chiTietChis = chiTietChis;
    }

}
