package com.poly.model;
// Generated Dec 7, 2019 5:52:52 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LoaiThu generated by hbm2java
 */
@Entity
@Table(name = "LoaiThu",
         schema = "dbo",
         catalog = "DuAn1"
)
public class LoaiThu implements java.io.Serializable {

    private int maloaithu;
    private String mota;
    private String tenloaithu;
    private Set<ChiTietThu> chiTietThus = new HashSet<ChiTietThu>(0);

    public LoaiThu() {
    }

    public LoaiThu(int maloaithu) {
        this.maloaithu = maloaithu;
    }

    public LoaiThu(int maloaithu, String mota, String tenloaithu, Set<ChiTietThu> chiTietThus) {
        this.maloaithu = maloaithu;
        this.mota = mota;
        this.tenloaithu = tenloaithu;
        this.chiTietThus = chiTietThus;
    }

    @Id
    @Column(name = "maloaithu", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public int getMaloaithu() {
        return this.maloaithu;
    }

    public void setMaloaithu(int maloaithu) {
        this.maloaithu = maloaithu;
    }

    @Column(name = "mota")
    public String getMota() {
        return this.mota;
    }

    public void setMota(String mota) {
        this.mota = mota;
    }

    @Column(name = "tenloaithu")
    public String getTenloaithu() {
        return this.tenloaithu;
    }

    public void setTenloaithu(String tenloaithu) {
        this.tenloaithu = tenloaithu;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "loaiThu")
    public Set<ChiTietThu> getChiTietThus() {
        return this.chiTietThus;
    }

    public void setChiTietThus(Set<ChiTietThu> chiTietThus) {
        this.chiTietThus = chiTietThus;
    }

}
